spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/trateme
    username: trateme
    password: trateme
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect