server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost/trateme
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
